##dubbo 的注册中心选为zookeeper
server:
  port: 9099
spring:
  dubbo:
   application:
     name: dubbo-prodcut-service
     registry: zookeeper://47.107.53.172:2181
   protocol:
     name: dubbo
     port: 20882
  application:
    name: prodcut-service
  datasource:
   url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
   username: root
   password: root
   driver-class-name: com.mysql.jdbc.Driver
  redis:
   host: 127.0.0.1
   port: 6379
   database: 0
   timeout: 2000



#rocketMQ 配置
rocketMq:
  nameServer:
    offline: 47.107.53.172:9876




#添加mybatis输出sql
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml


